# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='current_num',
        ),
    ]
