# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_remove_goods_current_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='current_num',
            field=models.IntegerField(default=0),
        ),
    ]
